spring:
  application:
    name: notes-server
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:h2:mem:testDB;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  flyway:
    #Essa propriedade serve para ativarmos o Flyway
    enabled: true
    #Essa propriedade para criar uma tabela com as migrações e assim ter acesso ao histórico de modificações.
    baseline-on-migrate: true
    locations: classpath:db/migration