spring:
  application:
    name: notes-server
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/notesDB
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:

    #Essa propriedade serve para ativarmos o Flyway
    enabled: true
    #Essa propriedade para criar uma tabela com as migrações e assim ter acesso ao histórico de modificações.
    baseline-on-migrate: true


server:
  port: 8081
